version: '3.6'

services:
    api.inlive:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - ./:/usr/app
        command: air
        container_name: api.inlive
        ports:
            - 9090:8080
        environment: 
            - "APPENV=development"
        networks:
            - local
        depends_on: 
            - postgres
    postgres:
        image: postgres:12.0-alpine
        environment:
            POSTGRES_DB: livestream
            POSTGRES_PASSWORD: livestream123
            POSTGRES_USER: livestream_user
            PGDATA: /var/lib/postgresql/data/asumsi-livestream
        container_name: postgres-livestream
        volumes:
            - .docker/postgres-data:/var/lib/postgresql/data/asumsi-livestream
            - .docker/database_scripts:/docker-entrypoint-initdb.d
            - .docker/seeding/seeds:/seeds
        ports:
            - "5432:5432"
        networks:
            - local

networks:
    local:
        driver: bridge